# Generated by Django 5.1.7 on 2025-03-28 19:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('programs', '0001_initial'),
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TempCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursemodel')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'temp_courses',
            },
        ),
        migrations.CreateModel(
            name='TempModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('is_public', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temps', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temps', to='universities.universitymodel')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temps', to='programs.programmodel')),
                ('courses', models.ManyToManyField(related_name='temps', through='temps.TempCourse', to='courses.coursemodel')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'temps',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='tempcourse',
            name='temp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temps.tempmodel'),
        ),
        migrations.AlterUniqueTogether(
            name='tempcourse',
            unique_together={('temp', 'course')},
        ),
    ]
