# Generated by Django 5.1.7 on 2025-03-28 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('temps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TempCourse',
            new_name='TempCourseModel',
        ),
    ]
